# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'fileutils'

# load server config from YAML file
CONFIGURATION_YAML = YAML.load_file('config.yaml')
PUPPET_HOME = ENV['PUPPET_HOME']
if PUPPET_HOME == nil
  puts 'ERROR! PUPPET_HOME is not defined.'
  exit(1)
end
HIERADATA_PATH = ENV['HIERA_HOME'] || File.join(PUPPET_HOME, 'hieradata')
PUPPET_FILESERVER_PATH = File.join(PUPPET_HOME, 'files')

$puppet_lib_install_script = <<EOF
   mkdir -p /etc/puppet/modules;
   if [ ! -d /etc/puppet/modules/stdlib ]; then
      puppet module install puppetlabs/stdlib
   fi
   mkdir -p /etc/facter/facts.d/
   public_ip=$(ip route get 192.168.100.1 | awk '{print $NF;exit}')
   echo "ipaddress=$public_ip" > /etc/facter/facts.d/public_ip.txt
EOF

puts "PUPPET_HOME set to #{PUPPET_HOME}"
puts "HIERADATA_PATH set to #{HIERADATA_PATH}"
puts "PUPPET_FILESERVER_PATH set to #{PUPPET_FILESERVER_PATH}"

Vagrant.configure(2) do |config|
  CONFIGURATION_YAML['servers'].each do |server|
    if defined?(server['enabled']) && server['enabled'] != false
      puts 'Provisioning VirtualBox with hostname: ', server['hostname']
      config.vm.define server['hostname'] do |server_config|
        server_config.vm.box = server['box']
        server_config.vm.host_name = server['hostname']
        server_config.vm.network :private_network, ip: server['ip']
        server_config.vm.synced_folder HIERADATA_PATH, '/puppet/hieradata', id: 'hieradata', type: 'rsync'
        server_config.vm.synced_folder PUPPET_FILESERVER_PATH, '/puppet/files', id: 'puppet_fileserver'
        memory = server['ram'] ? server['ram'] : 256
        cpu = server['cpu'] ? server['cpu'] : 1

        server_config.vm.provider :virtualbox do |vb|
          vb.name = server['hostname']
          vb.check_guest_additions = false
          vb.functional_vboxsf = false
          vb.gui = false
          vb.customize ['modifyvm', :id, '--memory', memory]
          vb.customize ['modifyvm', :id, '--cpus', cpu]
        end

        server_config.vm.provision :shell do |shell|
          shell.inline = $puppet_lib_install_script
        end

        server_config.vm.provision :puppet do |puppet|
          puppet.manifest_file = 'site.pp'
          puppet.manifests_path = File.join(PUPPET_HOME, 'manifests')
          puppet.module_path = File.join(PUPPET_HOME, 'modules')
          puppet.hiera_config_path = File.join(PUPPET_HOME, 'hiera.yaml')
          puppet.working_directory = '/puppet'
          puppet.options = %w(--verbose --fileserverconfig=/vagrant/fileserver.conf --debug --trace)

          # custom facts provided to Puppet
          puppet.facter = server['facters']
        end
      end
    end
  end
end
